### ISSUE TITLE
Dutch 9292.nl backend no longer working - fix in original?

### ISSUE THREAD

**Issue by dyraig** [poetaster/fahrplan#2]
In smurfy's repository of Fahrplan, I had raised the issue that the [Dutch 9292.nl backend is no longer working](https://github.com/smurfy/fahrplan/issues/286). Someone apparently already came up with a fix (see https://github.com/smurfy/fahrplan/pull/287) - did you by any chance include that in your version?

**Comment by poetaster** [comment]
I hadn't included those pulls. Just looking at it briefly it looks like it implements the newest apis. I'm testing ....

**Comment by poetaster** [comment]
Ok, I had to make a couple of corrections but it does work. I'm going to do a pre-release and upload the packages here if you would care to help test?

**Comment by poetaster** [comment]
I just noticed that times are screwy when walking is involved.

**Comment by dyraig** [comment]
I would love to help testing it, as having it back working would make me very happy... ;) Thanks a mil for working on this!

**Comment by poetaster** [comment]
https://github.com/poetaster/fahrplan/releases/tag/2.0.36
Binaries there or on openrepos https://openrepos.net/content/poetaster/fahrplan-fork
Chum coming right up.

**Comment by poetaster** [comment]
fixed with: https://github.com/poetaster/fahrplan/commit/706e78e6a9ef73fb5c6dc523f233214adb2424f3
