### ISSUE TITLE
delays not shown anymore

### ISSUE THREAD

**Issue by smatkovi** [poetaster/fahrplan#29]
first i thought oebb changed something that delays aren't shown anymore, but i just compiled the version from smurfy with corrected oebb url and saw that delays are still shown. so one change might have broken that feature...

**Comment by smatkovi** [comment]
it's because baseBinayrUrl hase been removed in parser_xmloebbat.cpp, adding it and changing ParserHafasXml to ParserHafasBinary results in a compiler error

**Comment by smatkovi** [comment]
oh it has been changed in parser_xmloebbat.h too, after changing that it compiles and gives delays again

**Comment by poetaster** [comment]
I think this is fixed with https://github.com/poetaster/fahrplan/commit/a988ac66b1939b190eba6b7b632497e4b0b98c9d

Thanks for the contribution and please close if the release works for you (worked for me but I've only done a quick test).
