### ISSUE TITLE
Backend OEBB (Austria) not working anymore

### ISSUE THREAD

**Issue by Norbert2022** [poetaster/fahrplan#3]

**Comment by Norbert2022** [comment]
As far as I can remember this backend worked untill the whole original SW stopped working under Sailfish 4.x

**Comment by poetaster** [comment]
I can confirm that it's not working in my last release. I'm working on the netherlands so I'll get back to this.

**Comment by Norbert2022** [comment]
Thank you. For many here in Austria, Fahrpaln was (and still would be) one of the most important everyday applications under Sailfish.

**Comment by poetaster** [comment]
Might take bit of time ;) Hopefully they haven't changed the entire api :)

**Comment by luchmhor** [comment]
Is it somehow realistic to tap into the providers from the Öffi repository, so it is a one time effort fahrplan would be up to date with all backends all the time:

https://gitlab.com/oeffi/public-transport-enabler/-/blob/master/src/de/schildbach/pte/OebbProvider.java

**Comment by poetaster** [comment]
The 9292 api's had been radically overhauled. The changes from https://github.com/smurfy/fahrplan/pull/287 that I modified to work are mostly new code. It's not finished yet, but won't take long. The 9292 branch is already usable with the dutch backend but 'flake'.

The Providers in de/shildbach/pte can be useful reference, but there is not way to use them directly.

**Comment by poetaster** [comment]
But, of course you're right that all backends that use: HafasClientInterfaceProvider will be fixed with an update to the ParserHafasXml.h and binary headers. I hope :)

**Comment by poetaster** [comment]
Testing:

https://github.com/smurfy/fahrplan/pull/285/files

**Comment by poetaster** [comment]
So, those changes work. The sbb backend needs work, but oebb basically works. It's odd in filtering names (Graz vs. Görlitz!) ... but Wien -> Innsbruck in 7 hours on the Zürich route seams reasonable :)

**Comment by luchmhor** [comment]
Thanks a lot, but there should be a connection Wien-Innsbruck in less than 4.5 hours every hour.

**Comment by poetaster** [comment]
> But there should be a connection Wien-Innsbruck in less than 4.5 hours every hour.

There's the RJX 564 which seems to get from Hbf to Hbf om 4:14. So it's looking like good data.

**Comment by poetaster** [comment]
https://github.com/poetaster/fahrplan/releases/tag/2.0.36
Binaries there or on openrepos https://openrepos.net/content/poetaster/fahrplan-fork
Chum coming right up.

**Comment by poetaster** [comment]
fixed with: https://github.com/poetaster/fahrplan/commit/706e78e6a9ef73fb5c6dc523f233214adb2424f3

**Comment by Norbert2022** [comment]
Great + THX. OEBB seems to work pretty fine so far.
