### ISSUE TITLE
Calendar event wrong in some cases (9292.nl related?)

### ISSUE THREAD

**Issue by dyraig** [poetaster/fahrplan#31]
While using Fahrplan with 9292,nl, I noticed another issue, this time with importing the journey into the agenda. Here's what I've seen:

Case 1, no walking:
- Leiden Centraal, departure: 23:23h
- Rotterdam Centraal, arrival: 00:15h
Importing the journey works

Case 2, walking at the end:
- Leiden Centraal, departure: 23:23h
- Rotterdam, Heer Bokelweg, arrival 00:24h (after walk)
Importing the journey works

Case 3, walking at the start and end:
- Wassenaarseweg, Leiden, departure: 23:13h
- Rotterdam, Heer Bokelweg, arrival 00:24h (after walk)
The event has no start time. If I do import it, the start time is set to 01/01/1970, 01:00h (which makes the even useless, of course).

Case 4 - same as case 3, but different time:
- Wassenaarseweg, Leiden, departure: 22:43h
- Rotterdam, Heer Bokelweg, arrival 23:54h (after walk)
The event has no start time. If I do import it, the start time is set to 01/01/1970, 01:00h (which makes the even useless, of course).

Somehow, when there is a walk at the start of the journey, the event is not created correctly.

**Comment by poetaster** [comment]
Confirmed. It's related to the way that legs of a journey are represented. The walk parts are ONLY duration. Which requires calculating times (was a pita for a journey) and it seems I've overlooked scanning back to the first leg with date time and subtracting walking AND saving that. hmmm. The time show correctly from the street adress, so it should be fixable.

**Comment by poetaster** [comment]
ah, I had a ticket related to this: #28

**Comment by poetaster** [comment]
https://github.com/poetaster/fahrplan/releases/tag/2.0.46

This should be fixed now. Please test as you have before and close this ticket if it's fixed.

Thanks a lot!

**Comment by dyraig** [comment]
Just tested some familiar scenarios and specifically Case 3/4 from above - seems like you've nailed it! Thank you very much indeed!
