### ISSUE TITLE
9292 backend walking times incorrect

### ISSUE THREAD

**Issue by poetaster** [poetaster/fahrplan#5]
Not sure if it's a calculation error or the values returned from the api.

**Comment by poetaster** [comment]
There is also the issue of first/last leg being walking. For duration, I'm working around this by skipping 1st or last when walking. Start and Arrival times also need to be done.

**Comment by dyraig** [comment]
Just installed 2.0.36 and tried some of my standard connections. I don't see any walking times given at all, nor are they taken into account for the duration. By departure and arrival times, I assume you mean the fact that no departure time is given when the first part of the journey is a walk and no arrival time is given when the last part of the journey is a walk? 'cause that is what I am seeing.

**Comment by poetaster** [comment]
> I assume you mean the fact that no departure time is given when the first part of the journey is a walk and no arrival time is given when the last part of the journey is a walk? 'cause that is what I am seeing.

Yes. It's an issue if Walk is the first element or the last.  I just tried random connections, so I'm no sure how often it happens. In any case we're also missing train details like Bicycle or reservation requirements, so I'll hopefully have a deeper idea of the nested fields. I think that Walking times are actually available.

**Comment by poetaster** [comment]
It's in 'Duration' for the leg.
