### ISSUE TITLE
Backend Switzerland (sbb.ch) doesn't work anymore

### ISSUE THREAD

**Issue by pherjung** [poetaster/fahrplan#6]
I get error :
```
Error parsing response from the server: unexpected character
```

And on terminal:
```
[D] expression for onParserErrorOccured:211 - Got error
[D] expression for onParserErrorOccured:212 - Error parsing response from the server: unexpected character
[D] expression for onParserErrorOccured:109 - Got error
[D] expression for onParserErrorOccured:110- Error parsing response from the server: unexpected character

As workaround, I use bahn.de as backend.

**Comment by poetaster** [comment]
It seems most of the backends are KO. I managed to get the 9292 dutch backend working with PR code from smurfy's repo. It still needs a bit of work and then I'll push that. 

My plan had been to look at austria first  and then switzerland.

**Comment by pherjung** [comment]
No hurry! Using bahn.de works fine for me.

**Comment by poetaster** [comment]
The sbb.ch backend is a completely new, rest, api:
https://developer.sbb.ch/apis/journey-service/documentation

And so, a complete rewrite.

**Comment by poetaster** [comment]
timetable.search.ch was merged in some time ago. Swiss backend is active again :)
