### ISSUE TITLE
9292.nl: duration miscalculated

### ISSUE THREAD

**Issue by dyraig** [poetaster/fahrplan#8]
While testing the new beta backend (THANK YOU!), I noticed that the calculation of the duration of the journey is somehow miscalculated. I've seen several cases:
- Journey from metro station to metro station (no transfers or walking involved): duration is given as 0:00
- Journey from bus stop to metro station (1 transfer between bus and metro): a duration is given, but the duration is neither "bus duration + metro duration" nor the complete duration - it's somewhere in between
- Same goes for any journey that has some walking at the beginning and/or end
I've compared the values with those given on the 9292.nl website - it looks as if the given duration is the complete duration *minus* the walking duration, at least for some connections (couldn't establish a really reliant pattern yet, sorry)

**Comment by poetaster** [comment]
Sorry to be so late in seeing this. I had noted in #5, that calculations were incorrect. Thanks for reporting!

**Comment by poetaster** [comment]
Found it:
```
    if (detail->getItem(detail->itemcount()-1)->train() == "Walk") {
        minutesEnd =  detail->getItem(detail->itemcount()-2)->arrivalDateTime();
    } else {
        minutesEnd =  detail->getItem(detail->itemcount()-1)->arrivalDateTime();
    }
    if (detail->getItem(0)->train() == "Walk") {
        minutesBegin =  detail->getItem(1)->arrivalDateTime();
    } else {
        minutesBegin =  detail->getItem(0)->arrivalDateTime();
    }
```
notice that departure time is never used

**Comment by poetaster** [comment]
Oh. dear. It was a bit more complicated. The current state renders all times correctly. But before I do a release, I'd also like to fix earlier and later.

**Comment by poetaster** [comment]
If you have the time/muse, compile this version.

**Comment by poetaster** [comment]
https://github.com/poetaster/fahrplan/releases/tag/2.0.43

Contains the fixes.

**Comment by dyraig** [comment]
Nice, thank you! Still haven't got round to set up an environment where I could compile Sailfish stuff (some point in the future when things have quietened down a bit maybe...), so I'll just be patient. ;)

**Comment by poetaster** [comment]
> Nice, thank you! Still haven't got round to set up an environment where I could compile Sailfish stuff (some point in the future when things have quietened down a bit maybe...), so I'll just be patient. ;)

Testing on builds and reporting is also a great help. Sometimes I miss a report and it takes too long to respond, but I'll do my best!
Thanks for reporting!

**Comment by poetaster** [comment]
Oh, it's up on chum and openrepos :)
